### ISSUE TITLE
language filtering leads to incomplete search results

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/registry-demo#13]
When searching for ["nta" in the Dutch](https://datasetregister.netwerkdigitaalerfgoed.nl/search.php#eyJ0IjoibnRhIiwiaSI6WyJkY3Q6dGl0bGUiXX0=) version of the demonstrator you get **4 results**, searching for ["nta" in the English](https://datasetregister.netwerkdigitaalerfgoed.nl/search.php?lang=en#eyJ0IjoibnRhIiwiaSI6WyJkY3Q6dGl0bGUiXX0=) version you get **3 results**.

The SPARQL query uses the language of the GUI to filter on the language of the title and description, like `FILTER(LANG(?title) = "" || LANGMATCHES(LANG(?title), "en"))`. The NTA/KB dataset has a title@nl and description@nl, so won't be selected in the English version.

**Comment by coret** [comment]
The [original query](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?name=&infer=true&sameAs=true&query=PREFIX%20dcat%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0APREFIX%20dct%3A%20%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20foaf%3A%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0ASELECT%20DISTINCT%20%3Fdataset%20%3Ftitle%20%3FpublisherName%20WHERE%20%7B%0A%20%20%20%20%3Fdataset%20a%20dcat%3ADataset%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20dct%3Atitle%20%3Ftitle%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20dct%3Apublisher%20%3Fpublisher%20.%0A%20%20%20%20%3Fpublisher%20foaf%3Aname%20%3FpublisherName%20.%0A%20%20%20%20FILTER(LANG(%3Ftitle)%20%3D%20%22%22%20%7C%7C%20LANGMATCHES(LANG(%3Ftitle)%2C%20%22en%22))%0A%20%20%20%20FILTER(LANG(%3FpublisherName)%20%3D%20%22%22%20%7C%7C%20LANGMATCHES(LANG(%3FpublisherName)%2C%20%22en%22))%0A%20%20%20%20FILTER%20CONTAINS(LCASE(%3Ftitle)%2C%22nta%22)%20.%0A%7D%20ORDER%20BY%20%3Ftitle) is:
```
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?dataset ?title ?publisherName WHERE {
    ?dataset a dcat:Dataset ;
             dct:title ?title ;
             dct:publisher ?publisher .
    ?publisher foaf:name ?publisherName .
    FILTER(LANG(?title) = "" || LANGMATCHES(LANG(?title), "nl"))
    FILTER(LANG(?publisherName) = "" || LANGMATCHES(LANG(?publisherName), "nl"))
    FILTER CONTAINS(LCASE(?title),"nta") .
} ORDER BY ?title
```

an [alternative version](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?name=&infer=true&sameAs=true&query=PREFIX%20dcat%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0APREFIX%20dct%3A%20%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20foaf%3A%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0ASELECT%20DISTINCT%20%3Fdataset%20%3Ftitle%20%3FpublisherName%20WHERE%20%7B%0A%20%20%20%20%3Fdataset%20a%20dcat%3ADataset%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20dct%3Apublisher%20%3Fpublisher%20.%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fdataset%20dct%3Atitle%20%3Fnltitle%20.%0A%20%20%20%20%20%20%20%20FILTER(langMatches(lang(%3Fnltitle)%2C%22nl%22)%20)%0A%20%20%20%20%7D%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fdataset%20dct%3Atitle%20%3F__title%20.%0A%20%20%20%20%20%20%20%20FILTER(langMatches(lang(%3F__title)%2C%22%22)%20)%0A%20%20%20%20%7D%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fdataset%20dct%3Atitle%20%3Fentitle%20.%0A%20%20%20%20%20%20%20%20FILTER(langMatches(lang(%3Fentitle)%2C%22en%22)%20)%0A%20%20%20%20%7D%0A%20%20%20%20BIND(%20COALESCE(%20%3Fnltitle%2C%20%3F__title%2C%20%3Fentitle%20)%20as%20%3Ftitle%20)%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fpublisher%20foaf%3Aname%20%3FnlpublisherName%20.%0A%20%20%20%20%20%20%20%20FILTER(langMatches(lang(%3FnlpublisherName)%2C%22nl%22)%20)%0A%20%20%20%20%7D%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fpublisher%20foaf%3Aname%20%3F__publisherName%20.%0A%20%20%20%20%20%20%20%20FILTER(langMatches(lang(%3F__publisherName)%2C%22%22)%20)%0A%20%20%20%20%7D%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3Fpublisher%20foaf%3Aname%20%3FenpublisherName%20.%0A%20%20%20%20%20%20%20%20FILTER(langMatches(lang(%3FenpublisherName)%2C%22en%22)%20)%0A%20%20%20%20%7D%0A%20%20%20%20BIND(%20COALESCE(%20%3FnlpublisherName%2C%20%3F__publisherName%2C%20%3FenpublisherName%20)%20as%20%3FpublisherName%20)%0A%20%20%20%20FILTER%20CONTAINS(LCASE(%3Ftitle)%2C%22nta%22)%20.%0A%7D%20ORDER%20BY%20%3Ftitle), using `COALESCE` is:
```
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?dataset ?title ?publisherName WHERE {
    ?dataset a dcat:Dataset ;
             dct:publisher ?publisher .
    OPTIONAL {
        ?dataset dct:title ?nltitle .
        FILTER(langMatches(lang(?nltitle),"nl") )
    }
    OPTIONAL {
        ?dataset dct:title ?__title .
        FILTER(langMatches(lang(?__title),"") )
    }
    OPTIONAL {
        ?dataset dct:title ?entitle .
        FILTER(langMatches(lang(?entitle),"en") )
    }
    BIND( COALESCE( ?nltitle, ?__title, ?entitle ) as ?title )
    OPTIONAL {
        ?publisher foaf:name ?nlpublisherName .
        FILTER(langMatches(lang(?nlpublisherName),"nl") )
    }
    OPTIONAL {
        ?publisher foaf:name ?__publisherName .
        FILTER(langMatches(lang(?__publisherName),"") )
    }
    OPTIONAL {
        ?publisher foaf:name ?enpublisherName .
        FILTER(langMatches(lang(?enpublisherName),"en") )
    }
    BIND( COALESCE( ?nlpublisherName, ?__publisherName, ?enpublisherName ) as ?publisherName )
    FILTER CONTAINS(LCASE(?title),"nta") .
} ORDER BY ?title
```

This is a better solution because, the number of search results doesn't differ between languages, but is bloated and more complex for the casual dataset searcher making her/his first SPARQL query...

**Comment by coret** [comment]
@ddeboer is this use of `COALESCE` what you had in mind?

**Comment by ddeboer** [comment]
More or less, yes, but this query can be simplified further by removing `COALESCE`:

```sparql
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT * WHERE {
    ?dataset a dcat:Dataset ;
             dct:publisher ?publisher .

    OPTIONAL {
        ?dataset dct:title ?title
        FILTER(langMatches(lang(?title), "nl"))        
    }

    OPTIONAL {
        ?dataset dct:title ?title
        FILTER(langMatches(lang(?title), "en"))        
    }
    
    OPTIONAL {
        ?dataset dct:title ?title
    }    
    
    OPTIONAL {
        ?publisher foaf:name ?publisherName
        FILTER(langMatches(lang(?publisherName), "nl"))                
    }    
    
    OPTIONAL {
        ?publisher foaf:name ?publisherName
        FILTER(langMatches(lang(?publisherName), "en"))                
    }    
    
    OPTIONAL {
        ?publisher foaf:name ?publisherName
    }   
}
```
