### ISSUE TITLE
Add facet

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/registry-demo#22]
Now, more datasets are returned in the query interface, there''s a need for facets, like organisations.

**Comment by ddeboer** [comment]
As an aside, I’d like to replace the demonstrator with a more fully fledged dataset browser. It may be advisable to implement the facets in a new UI app instead of the current PHP one.

**Comment by coret** [comment]
A client-side facet on organisations makes it easier to filter out "big contributors".

![image](https://github.com/netwerk-digitaal-erfgoed/registry-demo/assets/101820/ddd40524-22cd-40c4-8c7b-ba34cf831cbb)

**Comment by coret** [comment]
Define "fully fledged dataset browser"

**Comment by ddeboer** [comment]
Fully-faceted (publisher, license etc.), realtime-updating, UI application.

If you already have the facet, let’s add it to production! Am I right in assuming that you calculate the distinct publishers and counts client-side? Or are you doing some smart count SPARQL query?
