### ISSUE TITLE
show URL for detailed view of dataset descriptions more clearly

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/registry-demo#40]
Currently the URL for the detailed view of a dataset is only shown when you click on the location bar, default it only shows https://datasetregister.netwerkdigitaalerfgoed.nl/show.php without the request parameters. As a regular user I just now discovered that this hidden feature existed. I suggest to always show the full URL as people are used to copy these for reference. Or add a landingpage field with the full URL.

**Comment by ddeboer** [comment]
There is indeed a large number of [orphan datasets](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?savedQueryName=Orphan%20datasets&owner=admin). 

In this particular instance, I was able to re-register https://data.colonialcollections.nl/nmvw/collection-archives, which makes the metadata section visible. Perhaps something went wrong here with moving from the original registration URL https://colonial-heritage.triply.cc/nmvw/collection-archives

**Comment by EnnoMeijers** [comment]
You are right, my Vivaldi browser hides the parameters by default, clicking on the location bar makes them appear. I will close this issue.
