### ISSUE TITLE
incomplete result set for LOD datasets

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/registry-demo#41]
When using only the preset "Selecteer Linked Data formaten" not all relevant LOD datasets are shown, for example the "LOD Beelddocumenten (Regionaal Archief Nijmegen)" is not shown. The interface suggests that all relevant datasets are listed, is there a limit active?

**Comment by ddeboer** [comment]
Yes, as shown here:

<img width="1518" alt="image" src="https://github.com/user-attachments/assets/af774150-b447-43f5-bb70-05eb909ef6f4">

@coret Can we get rid of that limit?

**Comment by EnnoMeijers** [comment]
ah, that explains a lot!  

I can imagine we leave it in there when it leads to long loading times but it should than be clearly stated on the result page. In that case we should advise to combine searching for lod dataset in combination with other search options.

**Comment by EnnoMeijers** [comment]
I agree, but we should make clear on the result page that the user is looking at the first n results and not the complete list to avoid confusion.

**Comment by coret** [comment]
fixed by https://github.com/netwerk-digitaal-erfgoed/registry-demo/commit/e418944c153af9726a73d701ef8f3d754864c780

**Comment by EnnoMeijers** [comment]
Thanks for making this change but I would change the message to "groot aantal resultaten, de eerste 200 worden getoond, gebruik filters op SPARQL!"). It would also be nice if the optional filtering that is shown at the top would lead to a new query with a filter instead of filtering the result set. This would be helpful for the less SPARQL savy users and it leads to more interesting resullts.
